In [6]:
# Create pickle file
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [10]:
data=load_iris()# 
#data

In [11]:
x,y=load_iris(return_X_y=True)

In [12]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
d1=load_iris(as_frame=True)
type(d1)  # dictionary formte
d1['target']# only 1D formate it will shows
d1['data']#Input variables showing
d1.keys()#Key pairs showing
d1['frame'] # Here,with the help of 'frame'---> convert data into 2D dataframe
d2=pd.DataFrame(d1['frame'])# with the help of d2 we converted input and target variables in 2d dataframe
d2


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

### Model_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((105, 4), (45, 4), (105,), (45,))

In [18]:
LGmodel=LogisticRegression()

In [19]:
print(LGmodel)

LogisticRegression()


In [20]:
LGmodel.fit(x_train,y_train)

LogisticRegression()

### Evaluation

In [21]:
LGmodel.score(x_test,y_test)

0.9777777777777777

In [22]:
LGmodel.score(x_train,y_train)

0.9809523809523809

### Converting model into Pickle file

In [23]:
import pickle

In [24]:
pickle.dump(LGmodel,open('iris.pkl','wb'))

In [25]:
data['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [49]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### Finding Coef_ and intercept of model

In [26]:
LGmodel.coef_

array([[-0.43378071,  0.75702441, -2.24363013, -0.92999055],
       [ 0.58196982, -0.53638379, -0.13080007, -0.79885334],
       [-0.14818911, -0.22064061,  2.3744302 ,  1.72884389]])

In [27]:
LGmodel.intercept_

array([  9.18415763,   1.72229172, -10.90644935])

In [45]:
# Manual Inserting Prediction to test
x1_sepal_length=6.9
x2_sepal_width=3.1
x3_petal_length=5.4
x4_petal_width=2.1


In [50]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [52]:
result=LGmodel.predict([[x1_sepal_length,x2_sepal_width,x3_petal_length,x4_petal_width]])
result

array([2])

In [47]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [48]:
data['target_names'][result]

array(['virginica'], dtype='<U10')

### Test with User Input

In [55]:
# Now, Take User Input
x1_sepal_length=float(input())
x2_sepal_width=float(input())
x3_petal_length=float(input())
x4_petal_width=float(input())
result=LGmodel.predict([[x1_sepal_length,x2_sepal_width,x3_petal_length,x4_petal_width]])
print(f"Prediction={data['target_names'][result]}")

6.9
3.1
5.4
2.1
Prediction=['virginica']


In [56]:
# Now, Take User Input
x1_sepal_length=float(input())
x2_sepal_width=float(input())
x3_petal_length=float(input())
x4_petal_width=float(input())
result=LGmodel.predict([[x1_sepal_length,x2_sepal_width,x3_petal_length,x4_petal_width]])
print(f"Prediction={data['target_names'][result]}")

5.6
5.1
0.2
0.3
Prediction=['setosa']


### How to send to client

In [ ]:
To send this model to client we need to share pickle file--->for that reason load the file used 

In [57]:
import pickle

In [59]:
load_model=pickle.load(open('iris.pkl','rb'))
load_model

LogisticRegression()

In [60]:
# Now, Take User Input
x1_sepal_length=float(input())
x2_sepal_width=float(input())
x3_petal_length=float(input())
x4_petal_width=float(input())
result=load_model.predict([[x1_sepal_length,x2_sepal_width,x3_petal_length,x4_petal_width]])
result
print(f"Prediction={data['target_names'][result]}")

5.6
5.1
0.2
0.3
Prediction=['setosa']
